### ISSUE TITLE
你好，请问文字大小要怎么适配？

### ISSUE THREAD

**Issue by code-rebooter** [leavesCZY/SmallestWidthGenerator#2]

**Comment by leavesCZY** [comment]
@rayzeng0221 文字大小其实我也说不太准怎样适配才是最合适的，我只能说我目前的做法。我司项目提供的 UI 稿都是以 px 为单位，所以直接就用 SmallestWidthGenerator 生成的 px 作为文字的单位了，这样就不会受系统字体大小的影响了
